# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Child_Condition": types.Child_Condition,
    "stream_types.Child_Condition": stream_types.Child_Condition,

    "types.Happening": types.Happening,
    "stream_types.Happening": stream_types.Happening,

    "types.Obligation": types.Obligation,
    "stream_types.Obligation": stream_types.Obligation,

    "types.Output": types.Output,
    "stream_types.Output": stream_types.Output,

    "types.Zone": types.Zone,
    "stream_types.Zone": stream_types.Zone,


}