# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (14)
# #########################################################################

class Action(BaseModel):
    type: typing.Optional[typing.Union[str, str, str, str]] = None
    identifier: typing.Optional[str] = None
    help: typing.Optional[str] = None
    direction: typing.Optional[str] = None

class Child_Condition_PG(BaseModel):
    child_id: typing.Optional[str] = None
    reason: typing.Optional[str] = None
    required_MAT: typing.Optional[str] = None
    coordinate: typing.Optional["Coordinate"] = None

class Child_Condition_PT(BaseModel):
    child_id: typing.Optional[str] = None
    reason: typing.Optional[str] = None
    required_MAT: typing.Optional[str] = None
    zone_name: typing.Optional[str] = None
    zone_id: typing.Optional[str] = None

class Coordinate(BaseModel):
    x: typing.Optional[int] = None
    y: typing.Optional[int] = None

class Feedback(BaseModel):
    state: typing.Optional["RelevantStateElements"] = None
    violated_obligation: typing.Optional["MAT"] = None
    action: typing.Optional["Action"] = None

class Happening(BaseModel):
    zone_id: typing.Optional[str] = None
    reason: typing.Optional[str] = None
    required_MAT: typing.Optional[str] = None

class Happening_PT(BaseModel):
    zone_id: typing.Optional[str] = None
    reason: typing.Optional[str] = None
    required_MAT: typing.Optional[str] = None
    zone_name: typing.Optional[str] = None

class MAT(BaseModel):
    id: typing.Optional[str] = None
    required_MAT: typing.Optional[str] = None

class Obligation(BaseModel):
    obligation: typing.Optional[typing.Union["Happening", "Child_Condition_PT"]] = None

class Output_PG(BaseModel):
    type: typing.Optional[typing.Union[str, str, str, str]] = None
    identifier: typing.Optional[str] = None
    help: typing.Optional[str] = None
    target_coordinate: typing.Optional[typing.List[int]] = None
    reasoning: typing.Optional[str] = None

class Output_PT(BaseModel):
    type: typing.Optional[typing.Union[str, str, str]] = None
    identifier: typing.Optional[str] = None
    help: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None

class RelevantStateElements(BaseModel):
    agent_coordinate: typing.Optional["Coordinate"] = None
    child_conditions: typing.Optional[typing.List["Child_Condition_PG"]] = None
    happenings: typing.Optional[typing.List["Happening"]] = None

class Zone(BaseModel):
    zone_id: typing.Optional[str] = None

class Zone_PG(BaseModel):
    zone_id: typing.Optional[str] = None
    coordinates: typing.List["Coordinate"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
