# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Action": types.Action,
    "stream_types.Action": stream_types.Action,

    "types.Child_Condition_PG": types.Child_Condition_PG,
    "stream_types.Child_Condition_PG": stream_types.Child_Condition_PG,

    "types.Child_Condition_PT": types.Child_Condition_PT,
    "stream_types.Child_Condition_PT": stream_types.Child_Condition_PT,

    "types.Coordinate": types.Coordinate,
    "stream_types.Coordinate": stream_types.Coordinate,

    "types.Feedback": types.Feedback,
    "stream_types.Feedback": stream_types.Feedback,

    "types.Happening": types.Happening,
    "stream_types.Happening": stream_types.Happening,

    "types.Happening_PT": types.Happening_PT,
    "stream_types.Happening_PT": stream_types.Happening_PT,

    "types.MAT": types.MAT,
    "stream_types.MAT": stream_types.MAT,

    "types.Obligation": types.Obligation,
    "stream_types.Obligation": stream_types.Obligation,

    "types.Output_PG": types.Output_PG,
    "stream_types.Output_PG": stream_types.Output_PG,

    "types.Output_PT": types.Output_PT,
    "stream_types.Output_PT": stream_types.Output_PT,

    "types.RelevantStateElements": types.RelevantStateElements,
    "stream_types.RelevantStateElements": stream_types.RelevantStateElements,

    "types.Zone": types.Zone,
    "stream_types.Zone": stream_types.Zone,

    "types.Zone_PG": types.Zone_PG,
    "stream_types.Zone_PG": stream_types.Zone_PG,


}